name: Check and upgrade the GKE version of a specified GCP stack
description: "This action downloads the latest release of the GKE upgrade tool and runs it to upgrade the GKE version of a specified GCP stack."
inputs:
  kbc-stack:
    description: "KBC stack to upgrade"
    required: true
  gke-minor-version:
    description: "GKE minor version to upgrade to"
    required: false
  use-latest:
    description: "Use the latest GKE version"
    required: false
    default: "true"
  jira-ticket:
    description: "Related JIRA ticket"
    required: false
  specific-version:
    description: "Specific GKE version to upgrade to"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - uses: robinraju/release-downloader@v1.9
      with:
        repository: "keboola/gke-upgrade-tool"
        latest: true
    - name: Setup environment
      shell: bash
      run: |
        pip install gke*.tar.gz
        git config user.name github-actions
        git config user.email github-actions@github.com
        GKE_TOOL_ARGS=${{ inputs.kbc-stack }}/terraform/env.yaml
        if [ -n "${{ inputs.gke-minor-version }}" ]; then
          GKE_TOOL_ARGS+=" -m ${{ inputs.gke-minor-version }}"
        fi
        if [ "${{ inputs.use-latest }}" == "true" ]; then
          GKE_TOOL_ARGS+=" -l"
        fi
        if [ -n "${{ inputs.specific-version }}" ]; then
          GKE_TOOL_ARGS+=" -i ${{ inputs.specific-version }}"
        fi
        echo "GKE_TOOL_ARGS=${GKE_TOOL_ARGS}" >> $GITHUB_ENV
        if [ -n "${{ inputs.jira-ticket }}" ]; then
          PR_BODY=$(
          cat <<END_HEREDOC
        Relates to [${{ inputs.jira-ticket }}](https://keboola.atlassian.net/browse/${{ inputs.jira-ticket }}).
        END_HEREDOC
        )
        echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV
        fi
        if [ $(gh label list | grep -c ${{ inputs.kbc-stack }}) -eq 0 ]; then
          gh label create ${{ inputs.kbc-stack }}
        fi
    - name: Update env.yaml (Step 1 - Upgrade control plane and non-active nodepools)
      shell: bash
      run: |
        gke-upgrade-tool $GKE_TOOL_ARGS
        if [ -z "$(git diff)" ]; then
          echo "No changes in the env.yaml file. Exiting."
          exit 0
        else
          git checkout -b ${{ inputs.kbc-stack }}-gke-upgrade-1
          git commit -am "Upgrade GKE on ${{ inputs.kbc-stack }} #1 (Upgrade control plane and non-active nodepools)"
          git push origin --set-upstream ${{ inputs.kbc-stack }}-gke-upgrade-1
          PR_BODY=$(
          cat <<END_HEREDOC
        $PR_BODY

        Step 1: Upgrading control plane and non-active nodepools on **${{ inputs.kbc-stack }}** stack.
        END_HEREDOC
        )
          gh pr create --title "Upgrade GKE on ${{ inputs.kbc-stack }} #1 (Upgrade control plane and non-active nodepools)" --body "$PR_BODY" --label ${{ inputs.kbc-stack }} --base ${{ github.ref_name }} --head ${{ inputs.kbc-stack }}-gke-upgrade-1
        fi
    - name: Update env.yaml (Step 2 - Switch active/non-active nodepools)
      shell: bash
      run: |
        if [ -z "$(git branch --list ${{ inputs.kbc-stack }}-gke-upgrade-1)" ]; then
          echo "Branch ${{ inputs.kbc-stack }}-gke-upgrade-1 does not exist. Exiting."
          exit 0
        else
          gke-upgrade-tool $GKE_TOOL_ARGS --switch-active-only
          git checkout -b ${{ inputs.kbc-stack }}-gke-upgrade-2
          git commit -am "Upgrade GKE on ${{ inputs.kbc-stack }} #2 (Switch active/non-active nodepools)"
          git push origin --set-upstream ${{ inputs.kbc-stack }}-gke-upgrade-2
          PR_BODY=$(
          cat <<END_HEREDOC
        $PR_BODY

        Step 2: Switching active/non-active nodepools on **${{ inputs.kbc-stack }}** stack.
        END_HEREDOC
        )
          gh pr create --title "Upgrade GKE on ${{ inputs.kbc-stack }} #2 (Switch active/non-active nodepools)" --body "$PR_BODY" --label ${{ inputs.kbc-stack }} --base ${{ inputs.kbc-stack }}-gke-upgrade-1 --head ${{ inputs.kbc-stack }}-gke-upgrade-2
        fi
    - name: Update env.yaml (Step 3 - Upgrade now non-active nodepools)
      shell: bash
      run: |
        if [ -z "$(git branch --list ${{ inputs.kbc-stack }}-gke-upgrade-2)" ]; then
          echo "Branch ${{ inputs.kbc-stack }}-gke-upgrade-2 does not exist. Exiting."
          exit 0
        else
          gke-upgrade-tool $GKE_TOOL_ARGS
          git checkout -b ${{ inputs.kbc-stack }}-gke-upgrade-3
          git commit -am "Upgrade GKE on ${{ inputs.kbc-stack }} #3 (Upgrade now non-active nodepools)"
          git push origin --set-upstream ${{ inputs.kbc-stack }}-gke-upgrade-3
          PR_BODY=$(
          cat <<END_HEREDOC
        $PR_BODY

        Step 3: Upgrading now non-active nodepools on **${{ inputs.kbc-stack }}** stack.
        END_HEREDOC
        )
          gh pr create --title "Upgrade GKE on ${{ inputs.kbc-stack }} #3 (Upgrade now non-active nodepools)" --body "$PR_BODY" --label ${{ inputs.kbc-stack }} --base ${{ inputs.kbc-stack }}-gke-upgrade-2 --head ${{ inputs.kbc-stack }}-gke-upgrade-3
        fi
