name: Check and upgrade the GKE version

on:
  workflow_dispatch:
    inputs:
      kbc-stack:
        description: "KBC stack to upgrade, leave empty to upgrade all stacks"
        required: false
        type: string
      gke-minor-version:
        description: "GKE minor version to upgrade to"
        required: false
        type: string
      jira-ticket:
        description: "Related JIRA ticket"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  upgrade-all-gke-clusters:
    if: ${{ github.event.inputs.kbc-stack == null }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kbc-stacks: [test-stack, test-2-stack]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: "keboola/gke-upgrade-tool@michal-github-action-test"
        with:
          kbc-stack: ${{ matrix.kbc-stacks }}
          gke-minor-version: ${{ inputs.gke-minor-version }}
          jira-ticket: ${{ inputs.jira-ticket }}

  upgrade-single-gke-cluster:
    if: github.event.inputs.kbc-stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: "keboola/gke-upgrade-tool@michal-github-action-test"
        with:
          kbc-stack: ${{ inputs.kbc-stack }}
          gke-minor-version: ${{ inputs.gke-minor-version }}
          jira-ticket: ${{ inputs.jira-ticket }}
