name: Check and upgrade the GKE version

on:
  workflow_dispatch:
    inputs:
      kbc-stack:
        description: "KBC stack to upgrade, leave empty to upgrade all stacks"
        required: false
        type: string
      gke-minor-version:
        description: "GKE minor version to upgrade to"
        required: false
        type: string
      jira-ticket:
        description: "Related JIRA ticket"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  find-gke-clusters:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-gke-clusters.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Find GKE clusters
        id: find-gke-clusters
        run: |
          # Find all env.yaml files in the repository
          KBC_STACKS=$(find . -name "env.yaml" | grep -oP ".*(?=/terraform/env.yaml)" | sed 's|^\./||')
          # Find 'CLOUD_PROVIDER' in each env.yaml file and return the stack name if it's 'gcp'
          gcp_stacks=()
          for KBC_STACK in $KBC_STACKS; do
            CLOUD_PROVIDER=$(grep -oP "(?<=CLOUD_PROVIDER: \").*(?=\")" $KBC_STACK/terraform/env.yaml)
            if [ "$CLOUD_PROVIDER" == "gcp" ]; then
              gcp_stacks+=("$KBC_STACK")
            fi
          done
          json_array='[]'
          for stack in "${gcp_stacks[@]}"; do
            json_array=$(echo $json_array | jq --arg stack "$stack" '. + [{"gcp-stack": $stack}]')
          done
          json_object=$(echo $json_array | jq '{include: .}')
          echo $json_object
          echo "matrix=$(echo $json_object)" >> $GITHUB_OUTPUT
  output-job:
    runs-on: ubuntu-latest
    needs: find-gke-clusters
    strategy:
      matrix: ${{ fromJSON(needs.find-gke-clusters.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.gcp-stack }}
  # upgrade-all-gke-clusters:
  #   if: ${{ github.event.inputs.kbc-stack == null }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       kbc-stacks: [test-stack, test-2-stack]
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.1
  #     - uses: "keboola/gke-upgrade-tool@michal-github-action-test"
  #       with:
  #         kbc-stack: ${{ matrix.kbc-stacks }}
  #         gke-minor-version: ${{ inputs.gke-minor-version }}
  #         jira-ticket: ${{ inputs.jira-ticket }}

  # upgrade-single-gke-cluster:
  #   if: github.event.inputs.kbc-stack
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.1
  #     - uses: "keboola/gke-upgrade-tool@michal-github-action-test"
  #       with:
  #         kbc-stack: ${{ inputs.kbc-stack }}
  #         gke-minor-version: ${{ inputs.gke-minor-version }}
  #         jira-ticket: ${{ inputs.jira-ticket }}
