name: Check and upgrade the GKE version

on:
  workflow_dispatch:
    inputs:
      kbc-stack:
        description: "KBC stack to upgrade, leave empty to upgrade all stacks"
        required: false
        type: string
      gke-minor-version:
        description: "GKE minor version to upgrade to, leave empty to use minor version from env.yaml"
        required: false
        type: string
      jira-ticket:
        description: "Related JIRA ticket"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  find-gke-clusters:
    if: ${{ github.event.inputs.kbc-stack == null }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-gke-clusters.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Find GKE clusters
        id: find-gke-clusters
        run: |
          # Find all env.yaml files in the repository
          KBC_STACKS=$(find . -name "env.yaml" | grep -oP ".*(?=/terraform/env.yaml)" | sed 's|^\./||')
          # Find 'CLOUD_PROVIDER' in each env.yaml file and return the stack name if it's 'gcp'
          gcp_stacks=()
          for KBC_STACK in $KBC_STACKS; do
            CLOUD_PROVIDER=$(grep -oP "(?<=CLOUD_PROVIDER: \").*(?=\")" $KBC_STACK/terraform/env.yaml)
            if [ "$CLOUD_PROVIDER" == "gcp" ]; then
              gcp_stacks+=("$KBC_STACK")
            fi
          done
          # Prepare the matrix for the upgrade-all-gke-clusters job
          json_array='[]'
          for stack in "${gcp_stacks[@]}"; do
            json_array=$(echo $json_array | jq --arg stack "$stack" '. + [{"kbc-stack": $stack}]')
          done
          json_object=$(echo $json_array | jq '{include: .}')
          echo $json_object
          echo "matrix=$(echo $json_object)" >> $GITHUB_OUTPUT

  upgrade-all-gke-clusters:
    needs: find-gke-clusters
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.find-gke-clusters.outputs.matrix) }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: "keboola/gke-upgrade-tool@main"
        with:
          kbc-stack: ${{ matrix.kbc-stack }}
          gke-minor-version: ${{ inputs.gke-minor-version }}
          jira-ticket: ${{ inputs.jira-ticket }}

  upgrade-single-gke-cluster:
    if: github.event.inputs.kbc-stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: "keboola/gke-upgrade-tool@main"
        with:
          kbc-stack: ${{ inputs.kbc-stack }}
          gke-minor-version: ${{ inputs.gke-minor-version }}
          jira-ticket: ${{ inputs.jira-ticket }}